import React from 'react';
//JSX icon fonts
export const ico_question = <span><i className="fas fa-question"></i></span>
export const ico_cogs = <span><i className="fas fa-cogs"></i></span>
export const ico_user_check = <span><i className="fas fa-user-check"></i></span>
export const ico_search = <span><i className="fas fa-search"></i></span>
export const ico_toolbox = <span><i className="fas fa-toolbox"></i></span>
export const ico_bars = <span><i className="fas fa-bars"></i></span>
export const ico_moon = <span><i className="fas fa-moon"></i></span>
export const ico_text_height = <span><i className="fas fa-text-height"></i></span>
export const ico_sun = <span><i className="fas fa-sun"></i></span>
export const ico_envelope = <span><i className="fas fa-envelope"></i></span>
export const ico_phone = <span><i className="fas fa-phone"></i></span>
export const ico_thumbs_up = <span><i className="fas fa-thumbs-up"></i></span>
export const ico_ad = <span><i className="fas fa-ad"></i></span>
export const ico_at = <span><i className="fas fa-at"></i></span>
export const ico_paint_brush = <span><i className="fas fa-paint-brush"></i></span>
export const ico_cog = <span><i className="fas fa-cog"></i></span>
export const ico_android = <span><i className="fab fa-android"></i></span>
export const ico_apple = <span><i className="fab fa-apple"></i></span>
export const ico_code = <span><i className="fas fa-code"></i></span>
export const ico_react = <span><i className="fab fa-react"></i></span>
export const ico_microsoft = <span><i className="fab fa-microsoft"></i></span>
export const ico_linux = <span><i className="fab fa-linux"></i></span>
export const ico_database = <span><i className="fas fa-database"></i></span>
export const ico_globe_americas = <span><i className="fas fa-globe-americas"></i></span>
export const ico_folder = <span><i className="fas fa-folder"></i></span>
export const ico_user_friends = <span><i className="fas fa-user-friends"></i></span>
export const ico_paper_plane = <span><i className="fas fa-paper-plane"></i></span>
export const ico_terminal = <span><i className="fas fa-terminal"></i></span>
export const ico_robot = <span><i className="fas fa-robot"></i></span>
export const ico_user_clock = <span><i className="fas fa-user-clock"></i></span>
export const ico_bolt = <span><i className="fas fa-bolt"></i></span>
export const ico_facebook = <span><i className="fab fa-facebook-f"></i></span>
export const ico_instagram = <span><i className="fab fa-instagram"></i></span>
export const ico_twitter = <span><i className="fab fa-twitter"></i></span>
export const ico_linked_in = <span><i className="fab fa-linkedin-in"></i></span>
export const ico_font = <span><i className="fas fa-font"></i></span>
export const ico_magic = <span><i className="fas fa-magic"></i></span>
export const ico_camera_retro = <span><i className="fas fa-camera-retro"></i></span>
export const ico_times_circle = <span><i className="fas fa-times-circle"></i></span>
export const ico_times = <span><i className="fas fa-times"></i></span>
export const ico_play = <span><i className="fas fa-play"></i></span>
export const ico_pause = <span><i className="fas fa-pause"></i></span>
export const ico_check_circle = <span><i className="far fa-check-circle"></i></span>
export const ico_clock = <span><i className="far fa-clock"></i></span>
export const ico_chevron_right = <span><i className="fas fa-chevron-right"></i></span>
export const ico_chevron_left = <span><i className="fas fa-chevron-left"></i></span>
export const ico_user_tie = <span><i className="fas fa-user-tie"></i></span>
export const ico_blog = <span><i className="fas fa-blog"></i></span>
export const ico_newspaper = <span><i className="far fa-newspaper"></i></span>